### ISSUE TITLE
[REVIEW] Residuals from Python 2

### ISSUE THREAD

**Issue by ClaudMor** [mnets/pymnet#30]
Dear authors,

I noticed that in the tutorial on [Using NetworkX functions](https://mnets.github.io/pymnet/tutorial/nx.html#using-networkx-functions), some residuals from Python 2 are present:

```python
print net
```

```python
print map(nx.number_connected_components,models.er(1000,3*[0.005]).A.values())
```

Moreover the last line, when ported to python 3, does not return `[9, 11, 8]` as reported:

```python
print(map(nx.number_connected_components,models.er(1000,3*[0.005]).A.values()))
```
```nothing
<map object at 0x000001B26309D4B0>
```

**Comment by dataspider** [comment]
Thank you for catching these! I'll make a pass over all tutorials and ensure they are completely ported to python3. While I'm at it, I'll also translate the tutorials into Jupyter Notebooks (this was on my TODO list anyway). 
This should also take care of some of the other issues you identified.

**Comment by nwlandry** [comment]
You might try adding a Github action to test the notebooks (For example, see our [Github action](https://github.com/xgi-org/xgi/blob/main/.github/workflows/test.yml) in XGI)

**Comment by dataspider** [comment]
RST Tutorials reviewed for python2 remnants + other update needs:
- [x] index
- [x] installing
- [ ] isomorphisms
- [ ] networktypes
- [x] nx
- [ ] visualizing

**Comment by ClaudMor** [comment]
Thanks @dataspider for translating [this](https://mnets.github.io/pymnet/tutorial/nx.html) tutorial to python 3.

Anyway, I suggest changing the following line:

```python
print(map(nx.number_connected_components,models.er(1000,3*[0.005]).A.values()))
```

to

```python
print(map(nx.number_connected_components,pymnet.models.er(1000,3*[0.005]).A.values()))
```

to avoid an Exception being thrown. Moreover, its output is still:

```nothing
<map object at 0x0000013B1166CEB0>
```

instead of the documented

```nothing
[10, 9, 5]
```

**Comment by arashbm** [comment]
@ClaudMor Thanks, I manually fixed this tutorial for now, but tutorials will get a notebook revamp at some point soon.

**Comment by dataspider** [comment]
My bad (some of my local changes got lost in translation) – thanks @arashbm for fixing this (and yes, jupyter notebook versions are on the way)!

**Comment by dataspider** [comment]
Tutorials are now migrated to Python 3 and translated (where applicable) into Jupyter Notebooks, which are included in the docs via MyST_NB; see, e.g., [here](https://mnets.github.io/pymnet/tutorials/isomorphisms.html).

@nwlandry Thank you for the pointer to your GitHub action for testing notebooks – I am hoping to do cell-by-cell output comparisons and integrate these into our suite of unit tests (stub [here](https://github.com/mnets/pymnet/blob/master/pymnet/tests/tutorial_test.py)) but have yet to set make this work in our GitHub-action test environment. But since the docs now show the results of true notebook executions, I'll treat this as a separate issue and close this one.

**Comment by nwlandry** [comment]
@dataspider That sounds like a plan and certainly not essential for the review. Just a suggestion for future development.
